Repository ocurrent/ocaml-ci, pull requests merged in 2022-09, with the labels that each got.

#540 Document how to add the build status badge
  README.md
Labels: type/doc

#530 Adds refs to the urls used in the checks API.
  service/pipeline.ml
  web-ui/router.ml
Labels: type/enhancement

#538 Cleanup small things in build & step pages
  lib_client/run_time.ml
  test/test_run_time_client.ml
  web-ui/view/github.ml
  web-ui/view/template_v1.ml
Labels: type/refactor

#539 API: improve the history lookup
  lib/index.ml
  service/api_impl.ml
Labels: type/refactor
