Repository ocurrent/ocaml-ci, pull requests merged in 2023-01, with the labels that each got.

#399 Add dependency installation steps to README
  README.md
Labels: type/doc

#723 CSS line numbers for logs
  web-ui/static/css/style.css
  web-ui/static/js/add-repro-steps.js
  web-ui/static/js/log-highlight.js
  web-ui/view/step.ml
Labels: type/bug

#743 Add andreas missing picture
  deploy-data/github-organisations.txt
Labels: type/bug, type/ui

#721 Bug fix proposition for 703
  gitlab/pipeline.ml
  lib/cluster_build.ml
  lib/cluster_build.mli
  lib/index.ml
  lib/index.mli
  lib/pipeline.ml
  lib/pipeline.mli
  service/pipeline.ml
Labels: type/bug, context/causing-pain

#747 Web-ui: remanent bugs from the past
  web-ui/router.ml
  web-ui/static/fonts/inter.css
  web-ui/view/index.ml
  web-ui/view/step.ml
  web-ui/view/template.ml
Labels: type/bug, type/ui
