Repository ocurrent/ocaml-ci, pull requests merged in 2023-03, with the labels that each got.

#768 Revert back to local solver service
  lib/analyse.ml
  stack.yml
Labels: type/bug, context/discussion

#771 Refactor time in the CI
  Dockerfile.web
  dune-project
  lib/dune
  lib/index.ml
  lib/index.mli
  lib/run_time.ml
  lib/run_time.mli
  lib_client/dune
  lib_client/run_time.ml
  lib_client/run_time.mli
  ocaml-ci-client-lib.opam
  ocaml-ci-web.opam
  ocaml-ci.opam
  service/api_impl.ml
  test/service/dune
  test/service/test_index.ml
  test/service/test_lwt.ml
  test/service/test_run_time.ml
  test/service/test_run_time_client.ml
  test/web/dune
  test/web/test_build_representation.ml
  test/web/test_step_representation.ml
  web-ui/controller/api/dune
  web-ui/controller/api/git_forge.ml
  web-ui/controller/dune
  web-ui/controller/git_forge.ml
  web-ui/dune
  web-ui/representation/build.ml
  web-ui/representation/dune
  web-ui/representation/step.ml
  web-ui/view/api/dune
  web-ui/view/api/git_forge.ml
  web-ui/view/common.ml
  web-ui/view/dune
  web-ui/view/git_forge_intf.ml
  web-ui/view/history.ml
  web-ui/view/ref.ml
  web-ui/view/repo.ml
  web-ui/view/step.ml
  web-ui/view/step.mli
  web-ui/view/timestamps_durations.ml
  web-ui/view/timestamps_durations.mli
Labels: type/doc, type/refactor, type/ui

#781 Add missing sqlite3 deps
  Dockerfile.web
Labels: type/bug, context/causing-pain

#794 Logs over websockets
  .gitignore
  dune-project
  ocaml-ci-web.opam
  web-ui/controller/git_forge.ml
  web-ui/jsoo/dune
  web-ui/jsoo/main.ml
  web-ui/jsoo/process_chunk.ml
  web-ui/jsoo/steps_to_reproduce_build.ml
  web-ui/router.ml
  web-ui/static/css/style.css
  web-ui/static/js/add-repro-steps.js
  web-ui/static/js/dune
  web-ui/static/js/step-page-poll.js
  web-ui/view/dune
  web-ui/view/git_forge_intf.ml
  web-ui/view/step.ml
  web-ui/view/step.mli
Labels: type/enhancement, type/ui
