Repository ocurrent/ocaml-ci, pull requests merged in 2023-02, with the labels that each got.

#316 Replace calls to find with Bos.OS.Path.fold and Fpath
  dune-project
  lib/analyse.ml
  lib/dune
  ocaml-ci-service.opam
Labels: type/enhancement

#754 Colored logging for `ocaml-ci-local`
  service/local.ml
Labels: type/enhancement, type/ui

#750 Factorize organisation code
  web-ui/controller/index.ml
  web-ui/router.ml
  web-ui/view/index.ml
Labels: type/refactor, type/ui

#761 Factorisation for router.ml
  web-ui/controller/api/git_forge.ml
  web-ui/controller/git_forge.ml
  web-ui/router.ml
Labels: type/refactor

#760 Fix trailing slash in url
  web-ui/main.ml
Labels: type/bug, context/causing-pain
